services:
  db:
    image: postgres:16
    container_name: card_db
    environment:
      POSTGRES_DB: card_management
      POSTGRES_USER: lemongrb
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/card_management
      SPRING_DATASOURCE_USERNAME: lemongrb
      SPRING_DATASOURCE_PASSWORD: 1
    volumes:
      - ./logs:/app/logs
volumes:
  pgdata:
