spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_management
    username: lemongrb
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
